
## Assignment: NumPy Practice Notebook (Day 6)
Create a Google Colab Notebook demonstrating your understanding of NumPy and its use for numerical data analysis. The notebook should include examples of creating 1D, 2D, and 3D arrays, checking array dimensions and data types, indexing and slicing, reshaping arrays, generating arrays using functions such as zeros(), ones(), arange(), and linspace(), and performing mathematical and vectorized operations. Also demonstrate boolean masking, broadcasting, and common aggregate functions such as sum(), mean(), min(), max(), and median(). Keep the notebook well organized with clear headings, code, and outputs for each operation.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D array is:", arr1)
print("2D array is:")
print(arr2)
print("3D array is:")
print(arr3)

1D array is: [1 2 3 4]
2D array is:
[[1 2 3]
 [4 5 6]]
3D array is:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print("1D shape:", arr1.shape, "| dim:", arr1.ndim, "| type:", arr1.dtype)
print("2D shape:", arr2.shape,"| dim:", arr2.ndim, "| type:", arr2.dtype)
print("3D shape:", arr3.shape, "| dim:", arr3.ndim,"| type:", arr3.dtype)

1D shape: (4,) | dim: 1 | type: int64
2D shape: (2, 3) | dim: 2 | type: int64
3D shape: (2, 2, 2) | dim: 3 | type: int64


In [4]:
print("First element:", arr1[0])
print("Last element:", arr1[-1])
print("First two elements:", arr1[0:2])
print("Second row second col:", arr2[1, 2])
print("First row:", arr2[0])
print("Second column:", arr2[:, 1])

First element: 1
Last element: 4
First two elements: [1 2]
Second row second col: 6
First row: [1 2 3]
Second column: [2 5]


In [5]:
arr4 = np.arange(1, 13)
print("Normal array:", arr4)
print("Reshape to 3 rows 4 cols:")
print(arr4.reshape(3, 4))
print("Reshape to 2 rows 6 cols:")
print(arr4.reshape(2, 6))

Normal array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape to 3 rows 4 cols:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape to 2 rows 6 cols:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
z = np.zeros((2, 3))
o = np.ones((2, 3))
a = np.arange(0, 10, 2)
l = np.linspace(0, 1, 5)

print("zeros result:")
print(z)
print("ones result:")
print(o)
print("arange result:", a)
print("linspace result:", l)

zeros result:
[[0. 0. 0.]
 [0. 0. 0.]]
ones result:
[[1. 1. 1.]
 [1. 1. 1.]]
arange result: [0 2 4 6 8]
linspace result: [0.   0.25 0.5  0.75 1.  ]


In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("x is:", x)
print("y is:", y)
print("x + y is:", x + y)
print("x - y is:", x - y)
print("x * y is:", x * y)
print("x / y is:", x / y)
print("x power 2 is:", x ** 2)
print("square root of x is:", np.sqrt(x))

x is: [1 2 3]
y is: [4 5 6]
x + y is: [5 7 9]
x - y is: [-3 -3 -3]
x * y is: [ 4 10 18]
x / y is: [0.25 0.4  0.5 ]
x power 2 is: [1 4 9]
square root of x is: [1.         1.41421356 1.73205081]


In [8]:
marks = np.array([45, 80, 92, 33, 67, 55])
passed = marks >= 50

print("Marks are:", marks)
print("Pass mask is:", passed)
print("Passed marks are:", marks[passed])
print("Failed marks are:", marks[~passed])

Marks are: [45 80 92 33 67 55]
Pass mask is: [False  True  True False  True  True]
Passed marks are: [80 92 67 55]
Failed marks are: [45 33]


In [9]:
a = np.array([1, 2, 3])
print("a is:", a)
print("a + 10 is:", a + 10)

b = np.array([[1], [2], [3]])
c = np.array([10, 20, 30])
print("b is (3 rows 1 col):")
print(b)
print("c is:", c)
print("b + c broadcast result is:")
print(b + c)

a is: [1 2 3]
a + 10 is: [11 12 13]
b is (3 rows 1 col):
[[1]
 [2]
 [3]]
c is: [10 20 30]
b + c broadcast result is:
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
d = np.array([10, 20, 30, 40, 50])

print("d is:", d)
print("Sum is:", np.sum(d))
print("Mean is:", np.mean(d))
print("Min is:", d.min())
print("Max is:", d.max())
print("Median is:", np.median(d))

d is: [10 20 30 40 50]
Sum is: 150
Mean is: 30.0
Min is: 10
Max is: 50
Median is: 30.0


: 